//
//  MainViewControllerViewController.swift
//  mapApp
//
//  Created user on 5/18/20.
//  Copyright © 2020 Vinova.Train.mapApp. All rights reserved.
//
//  Template generated by Edward
//

// MVVM hay MVP?
// Co truyen du lieu tu V -> Model
// Mot model dung cho nhieu View

import UIKit

protocol goToTheMap {
    func show(whatMap: String)
}

class MainViewControllerViewController: UIViewController, MainViewControllerViewProtocol {

	var presenter: MainViewControllerPresenterProtocol

	init(presenter: MainViewControllerPresenterProtocol) {
        self.presenter = presenter
        super.init(nibName: "MainViewControllerViewController", bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    //init
    
    lazy var tableViewController = TableViewController()
    
    //end init
	override func viewDidLoad() {
        super.viewDidLoad()

        presenter.view = self
        presenter.viewDidLoad()
        
        //self.addChild(tableViewController)
        configureTableView()
    }
    
    func configureTableView(){
        self.view.addSubview(tableViewController.tableView)
    }
    

}
