//
//  MainViewControllerPresenter.swift
//  mapApp
//
//  Created user on 5/18/20.
//  Copyright © 2020 Vinova.Train.mapApp. All rights reserved.
//
//  Template generated by Edward
//

import Foundation

// MARK: View -
protocol MainViewControllerViewProtocol: class {

}

// MARK: Presenter -
protocol MainViewControllerPresenterProtocol: class {
	var view: MainViewControllerViewProtocol? { get set }
    func viewDidLoad()
}

class MainViewControllerPresenter: MainViewControllerPresenterProtocol {

    weak var view: MainViewControllerViewProtocol?

    func viewDidLoad() {

    }
}
